create table if not exists public.feedbacks (
  id bigint generated by default as identity primary key,
  name text not null,
  institution text,
  designation text,
  rating integer not null check (rating between 1 and 5),
  liked text,
  improve text,
  suggestions text,
  signature text
);

alter table public.feedbacks enable row level security;

revoke all on public.feedbacks from anon, authenticated;
grant all on public.feedbacks to service_role;
